ALTER TABLE professionals DROP COLUMN IF EXISTS zone;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS home_address TEXT;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS home_lat DOUBLE PRECISION;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS home_lng DOUBLE PRECISION;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS radius_km INTEGER;

ALTER TABLE users ADD COLUMN IF NOT EXISTS home_address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS home_lat DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS home_lng DOUBLE PRECISION;
